### PR TITLE
Added chardet to detect the encoding of the content

### PR DESCRIPTION
**Pull request by Nishantbhagat57**
When running urless on a txt file I encountered this error:
```ERROR processInput 2 'utf-8' codec can't decode byte 0xac in position 5030: invalid start byte```

The error message is indicating that Python is trying to decode a file as utf-8 but it is encountering a byte (in this case, `0xac`) which is not valid for utf-8 encoding.

To fix this issue I have modified the ```processInput()``` function to use ```chardet``` to handle encoding/decoding issues without modifying any content. ```chardet``` can help to detect the encoding of the content. We can use that encoding to open the file, rather than blindly assuming ```utf-8```.

#### Before modifications:
Screenshot urless 2

#### After modifications:
Screenshot urless 1

### CODE REVIEW

**Comment by Nishantbhagat57** [comment]
ping @xnl-h4ck3r

**Comment by xnl-h4ck3r** [comment]
Hey @Nishantbhagat57 , thanks for the pull request! This looks great! I just need to try it out locally first to make sure.
There seem to be 2 commits for setup.py though... the second having  url="https://github.com/Nishantbhagat57/urless", so I guess that commit should be removed
Thanks. I'll get back to you after I'ce tested

**Comment by Nishantbhagat57** [comment]
Hey there, thank you for reviewing this! My bad, the last commit regarding the URL change was intended for my personal fork and ended up in this PR inadvertently. Didn't think it would sneak into this PR :|

**Comment by xnl-h4ck3r** [comment]
> Hey there, thank you for reviewing this! My bad, the last commit regarding the URL change was intended for my personal fork and ended up in this PR inadvertently. Didn't think it would sneak into this PR :|

Can you remove that commit from the pull request?
Also, can you change the following as part of the request:
- Change README.md to say `v1.1` instead of `v1.0`
- Change image/__init__.py to say `v1.1` intead of `v1.0`
- Add the v1.1 and description of the change to CHANGELOG.md

Thanks!

**Comment by xnl-h4ck3r** [comment]
Also, I have a question... you mentioned that character `0xac` was in the file. That appears to be the symbol `¬`. Is that a valid character that was in a URL?

**Comment by Nishantbhagat57** [comment]
Hi @xnl-h4ck3r I have implemented the changes.

Now, about the symbol ```¬``` or character ```0xac``` you asked about, it was indeed found in the URL as follows: ```https://app.example.com/icicleViews/icicleCustomerPortrait/Ã¢â‚¬â€¹addwarterMark.js```

Even though the endpoint isn't correct, which could be categorized as a false positive, I believe ```urless``` should still effectively manage such instances. It simply threw an error in this case without attempting to ```deduplicate``` or ```de-clutter``` the URLs. In my case, I'm using ```urless``` as a part of an automation workflow, and it's essential that the script operates efficiently in all cases, regardless of some data portions being invalid.

That's why I suggest continuing with the chardet modification despite the input error - it maintains our ability to handle encoding/decoding issues effectively :)

**Comment by Nishantbhagat57** [comment]
@xnl-h4ck3r I don't know why it's saying ```ModuleNotFoundError: No module named 'chardet' ```

But you can try these things:

1. If you are testing the ```urless.py``` python script like ```sudo python3 urless.py -i input.txt -o output.txt``` then maybe ```chardet``` isn't installed for python that's on sudo, try the command without sudo.
2. Reinstall ```Python3```. I always use Homebrew to do this:
```/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"```
```(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/$USER/.bashrc```
```eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"```
```brew install python3```
```pip3 install chardet argparse pyyaml termcolor urlparse3```

I again tested the modified script and it works perfectly without issue in my environment

**Comment by xnl-h4ck3r** [comment]
Can you run these and let me know what versions you have?
```
python --version
chardet --version
```

**Comment by Nishantbhagat57** [comment]
Screenshot 2023-10-31 204552


> Can you run these and let me know what versions you have?
> 
> ```
> python --version
> chardet --version
> ```

**Comment by xnl-h4ck3r** [comment]
Thank you. Sorry this is taking so long to sort out.
When I run `pip3 show chardet` I get the same output as you, and see version 5.2.0. However, if I run `chardet --version` I get `chardet 3.0.4`. What do you get for `chardet --version`?

**Comment by Nishantbhagat57** [comment]
> Thank you. Sorry this is taking so long to sort out. When I run `pip3 show chardet` I get the same output as you, and see version 5.2.0. However, if I run `chardet --version` I get `chardet 3.0.4`. What do you get for `chardet --version`?

Screenshot 2023-11-01 191454

**Comment by xnl-h4ck3r** [comment]
> > Thank you. Sorry this is taking so long to sort out. When I run `pip3 show chardet` I get the same output as you, and see version 5.2.0. However, if I run `chardet --version` I get `chardet 3.0.4`. What do you get for `chardet --version`?
> 
> Screenshot 2023-11-01 191454

I get exactly the same, which although very strange, doesn't help mr figure out why I can't get mine to run with chardet :(

**Comment by xnl-h4ck3r** [comment]
Hey @Nishantbhagat57. Sorry to go quiet on this... I am still trying to figure out what the problem is. It's def something on my setup rather than your changes obviously. I still need to fix it properly on mine to test properly first. Thanks for you patience

**Comment by xnl-h4ck3r** [comment]
> > Thank you. Sorry this is taking so long to sort out. When I run `pip3 show chardet` I get the same output as you, and see version 5.2.0. However, if I run `chardet --version` I get `chardet 3.0.4`. What do you get for `chardet --version`?
> 
> Screenshot 2023-11-01 191454

I get exactly the same, which although very strange, doesn't help mr figure out why I can't get mine to run with chardet :(

**Pull request merged**
